### ISSUE TITLE
Can I use variables to access a key?

### ISSUE THREAD

**Issue by FunkyLoveCow** [cdgriffith/Box#75] opened 2019-04-15 03:36 UTC
I have a gigantic JSON object being returned via an API call. I am really only interested in a few fields in this response object. I'm trying to set up a config file of some kind that I can use to only get the fields I need. 

```
    fields:
        - field1
        - field2
        - field3.subfield1
```

This is the config I'm thinking, but it's not set in stone. 

This works for the top level elements:

```
devices = {
        'field1': 'Value of F1',
        'field2': 'Value of F2',
        'field3': [
                {
                    'subfield1': 'Value of subfield1',
                    'subfield2': 'Value of subfield2'
                }
            ],
        'field4': 'Not wanted'
    }

wanted_fields = ['field1', 'field2', 'field3.subfield1']

box_device = Box(devices)
for field in wanted_fields:
    print("{field} => {value}".format(field=field, value=box_device[field]))
```

Output:

```
field1 => Value of F1
field2 => Value of F2
Traceback (most recent call last):
  File "/home/myuser/.virtualenvs/jsontests/lib/python3.6/site-packages/box.py", line 412, in __getitem__
    value = super(Box, self).__getitem__(item)
KeyError: 'field3.subfield1'
```

This makes sense, because the dictionary path to that key is actually `box_device['field3']['subfield1']` 

However, if I attempt to change the print statement to use `field` as a variable, I get this error:

```
Traceback (most recent call last):
  File "box_test.py", line 33, in <module>
    print("{field} => {value}".format(field=field, value=box_device.field))
  File "/home/myuser/.virtualenvs/jsontests/lib/python3.6/site-packages/box.py", line 511, in __getattr__
    raise BoxKeyError(str(err))
box.BoxKeyError: "'Box' object has no attribute 'field'"
```

---

Question:

How can I access keys and sub-keys in a variable manner? I'd like something like `mybox.field` where `field` is a string containing keys I care about and that can be multileveled (ie. `field` could be `field1` or `field2.subfield1`)  I really would like to use dot notation to do this so that I can have clean and easy to understand configuration files.

**Comment by cdgriffith** [comment] 2019-04-15 14:25
This is actually something I would like to implement when possible, duplicate of https://github.com/cdgriffith/Box/issues/57

**Closed by cdgriffith** 2019-04-15 14:25 UTC
